### PR TITLE
Fix LB issues

### LINKED ISSUE #100: baremetal_database_db_system does not support characterSet, ncharacterSet
## Description of the bug:
baremetal_database_db_system does not support characterSet, ncharacterSet

## A self-contained terraform file that reproduces the issue:

API supports this

https://docs.us-phoenix-1.oraclecloud.com/api/#/en/database/20160918/requests/CreateDatabaseDetails

### LINKED ISSUE #119: data.baremetal_objectstorage_objects: The delimiter parameter '' is not supported
## Description of the bug:
Listing bucket contents with data.baremetal_objectstorage_objects dies with the following error:

```
Error applying plan:

1 error(s) occurred:

* data.baremetal_objectstorage_objects.bucket: data.baremetal_objectstorage_objects.bucket: Code: InvalidObjectName; OPC Request ID: 72d88049-5012-73b2-911d-9550065dfb2e; Message: The delimiter parameter '' is not supported
```

## A self-contained terraform file that reproduces the issue:

```
/*
 * Bucket
 */
 
variable "bucket-name" {
  default = "os-test"
}

resource "baremetal_objectstorage_bucket" "bucket" {
  name           = "${var.bucket-name}"
  compartment_id = "${var.compartment_ocid}"
  namespace      = "${data.baremetal_objectstorage_namespace.t.namespace}"

  metadata = {
    "foo" = "bar"
  }
}

/*
 * Object
 */
 
variable "object-name" {
  default = "os-object"
}

resource "baremetal_objectstorage_object" "object" {
  object    = "${var.object-name}"
  namespace = "${baremetal_objectstorage_bucket.bucket.namespace}"
  bucket    = "${baremetal_objectstorage_bucket.bucket.name}"
  content   = "${file("${path.module}/ostest.tf")}"

  metadata = {
    "bar" = "baz"
  }
}

/*
 * List Objects
 */

data "baremetal_objectstorage_objects" "bucket" {
  namespace = "${baremetal_objectstorage_bucket.bucket.namespace}"
  bucket    = "${baremetal_objectstorage_bucket.bucket.name}"
}

output "bucket-objects" {
  value = "${data.baremetal_objectstorage_objects.bucket.objects}"
}

/*
 * Configuration Variables
 */

variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}

/*
 * Bare Metal Provider
 */

provider "baremetal" {
  tenancy_ocid     = "${var.tenancy_ocid}"
  user_ocid        = "${var.user_ocid}"
  fingerprint      = "${var.fingerprint}"
  private_key_path = "${var.private_key_path}"
}

data "baremetal_objectstorage_namespace" "t" {}

```

### LINKED ISSUE #131: Creating a TCP lb_listener fails with invalid SSL config error
## Description of the bug:
terraform v0.9.4, bmprovider v1.0.12

This is a continuation of the test in #129 
Append the following to the loadbalancer.tf file:

```
resource "baremetal_load_balancer_listener" "port-2379" {
  load_balancer_id         = "${baremetal_load_balancer.lb-etcd.id}"
  name                     = "port-2379"
  default_backend_set_name = "${baremetal_load_balancer_backendset.lb-etcd-2379.id}"
  port                     = 2379
  protocol                 = "TCP"
}
```

screen shot 2017-05-30 at 13 55 15

### LINKED ISSUE #132: lb_listener fails with invalid SSL config error
## Description of the bug:
TF provider v1.0.12

baremetal_load_balancer_listener resource fails with ssl error in the work_req. No specific error message I see in the debug log

## A self-contained terraform file that reproduces the issue:

$ cat lbaaas_listener.tf 
{
  "resource": {
    "baremetal_load_balancer_listener": {
      "jmtfenv3-listener": {
        "load_balancer_id": "ocid1..........",
        "name": "jmtfenv3-listener",
        "default_backend_set_name": "jmtfenv3-backendset",
        "port": "8080",
        "protocol": "HTTP"
      }
    }
  }
}

Your plan was also saved to the path below. Call the "apply" subcommand
with this plan file and Terraform will exactly execute this execution
plan.

Path: jmtfenv3.plan

+ baremetal_load_balancer_listener.jmtfenv3-listener
    default_backend_set_name: "jmtfenv3-backendset"
    load_balancer_id:         "ocid1............."
    name:                     "jmtfenv3-listener"
    port:                     "8080"
    protocol:                 "HTTP"
    state:                    "<computed>"

Plan: 1 to add, 0 to change, 0 to destroy.
2017/05/30 20:22:49 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/05/30 20:22:49 [DEBUG] plugin: /home/opc/terraform/bm_plugin/linux_amd64/terraform-provider-baremetal: plugin process exited

$ terraform apply jmtfenv3.plan
2017/05/30 20:22:57 [INFO] Terraform version: 0.9.4  277bbf65d1141207dbb30485bf124b1dba08f80f
2017/05/30 20:22:57 [INFO] Go runtime version: go1.8
2017/05/30 20:22:57 [INFO] CLI args: []string{"/usr/bin/terraform", "apply", "jmtfenv3.plan"}
2017/05/30 20:22:57 [DEBUG] Detected home directory from env var: /home/opc
2017/05/30 20:22:57 [DEBUG] Detected home directory from env var: /home/opc
2017/05/30 20:22:57 [DEBUG] Attempting to open CLI config file: /home/opc/.terraformrc
2017/05/30 20:22:57 [INFO] CLI command args: []string{"apply", "jmtfenv3.plan"}
2017/05/30 20:22:57 [INFO] command: initializing local backend from plan (not set)
2017/05/30 20:22:57 [INFO] command: backend initialized: *local.Local
2017/05/30 20:22:57 [INFO] backend/local: starting Apply operation
2017/05/30 20:22:57 [INFO] terraform: building graph: GraphTypeApply
2017/05/30 20:22:57 [DEBUG] Resource state not found for "baremetal_load_balancer_listener.jmtfenv3-listener": baremetal_load_balancer_listener.jmtfenv3-listener
2017/05/30 20:22:57 [DEBUG] ReferenceTransformer: "baremetal_load_balancer_listener.jmtfenv3-listener" references: []
2017/05/30 20:22:57 [DEBUG] ReferenceTransformer: "provider.baremetal" references: []
2017/05/30 20:22:57 [DEBUG] Starting graph walk: walkApply
2017/05/30 20:22:57 [DEBUG] dag/walk: added new vertex: "root"
2017/05/30 20:22:57 [DEBUG] dag/walk: added new vertex: "baremetal_load_balancer_listener.jmtfenv3-listener"
2017/05/30 20:22:57 [DEBUG] dag/walk: added new vertex: "provider.baremetal"
2017/05/30 20:22:57 [DEBUG] dag/walk: added new vertex: "meta.count-boundary (count boundary fixup)"
2017/05/30 20:22:57 [DEBUG] dag/walk: added new vertex: "provider.baremetal (close)"
2017/05/30 20:22:57 [DEBUG] dag/walk: added edge: "baremetal_load_balancer_listener.jmtfenv3-listener" waiting on "provider.baremetal"
2017/05/30 20:22:57 [DEBUG] dag/walk: added edge: "meta.count-boundary (count boundary fixup)" waiting on "baremetal_load_balancer_listener.jmtfenv3-listener"
2017/05/30 20:22:57 [DEBUG] dag/walk: added edge: "provider.baremetal (close)" waiting on "baremetal_load_balancer_listener.jmtfenv3-listener"
2017/05/30 20:22:57 [DEBUG] dag/walk: added edge: "root" waiting on "meta.count-boundary (count boundary fixup)"
2017/05/30 20:22:57 [DEBUG] dag/walk: added edge: "root" waiting on "provider.baremetal (close)"
2017/05/30 20:22:57 [DEBUG] dag/walk: dependencies changed for "baremetal_load_balancer_listener.jmtfenv3-listener", sending new deps
2017/05/30 20:22:57 [DEBUG] dag/walk: dependencies changed for "meta.count-boundary (count boundary fixup)", sending new deps
2017/05/30 20:22:57 [DEBUG] dag/walk: dependencies changed for "provider.baremetal (close)", sending new deps
2017/05/30 20:22:57 [DEBUG] dag/walk: dependencies changed for "root", sending new deps
2017/05/30 20:22:57 [DEBUG] Detected home directory from env var: /home/opc
2017/05/30 20:22:57 [DEBUG] dag/walk: walking "provider.baremetal"
2017/05/30 20:22:57 [DEBUG] vertex 'root.provider.baremetal': walking
2017/05/30 20:22:57 [DEBUG] vertex 'root.provider.baremetal': evaluating
2017/05/30 20:22:57 [TRACE] [walkApply] Entering eval tree: provider.baremetal
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalSequence
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalInitProvider
2017/05/30 20:22:57 [DEBUG] plugin: starting plugin: /home/opc/terraform/bm_plugin/linux_amd64/terraform-provider-baremetal []string{"/home/opc/terraform/bm_plugin/linux_amd64/terraform-provider-baremetal"}
2017/05/30 20:22:57 [DEBUG] plugin: waiting for RPC address for: /home/opc/terraform/bm_plugin/linux_amd64/terraform-provider-baremetal
2017/05/30 20:22:57 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:57 [INFO] terraform-provider-baremetal v1.0.12
2017/05/30 20:22:57 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:57 [DEBUG] plugin: plugin address: unix /tmp/plugin320911773
2017/05/30 20:22:57 [DEBUG] root: eval: terraform.EvalNoop
2017/05/30 20:22:57 [DEBUG] root: eval: terraform.EvalNoop
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalOpFilter
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalSequence
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalGetProvider
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalInterpolate
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalBuildProviderConfig
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalSetProviderConfig
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalOpFilter
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalSequence
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalConfigProvider
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalDiff
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalReadDiff
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalCompareDiff
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalGetProvider
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalReadState
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalApplyPre
baremetal_load_balancer_listener.jmtfenv3-listener: Creating...
  default_backend_set_name: "" => "jmtfenv3-backendset"
  load_balancer_id:         "" => "ocid1.loadbalancer.oc1.h2atkua"
  name:                     "" => "jmtfenv3-listener"
  port:                     "" => "8080"
  protocol:                 "" => "HTTP"
  state:                    "" => "<computed>"
2017/05/30 20:22:57 [DEBUG] root: eval: *terraform.EvalApply
2017/05/30 20:22:57 [DEBUG] apply: baremetal_load_balancer_listener.jmtfenv3-listener: executing Apply
2017/05/30 20:22:57 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:57 [DEBUG] No meta timeoutkey found in Apply()
2017/05/30 20:22:57 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:57 [DEBUG] Waiting for state to become: [SUCCEEDED_WORK_REQUEST SUCCEEDED FAILED]
2017/05/30 20:22:58 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:58 [DEBUG] crud.BaseCrud.setState: state: "ACCEPTED"
2017/05/30 20:22:58 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:58 [TRACE] Waiting 200ms before next try
2017/05/30 20:22:58 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:58 [DEBUG] crud.BaseCrud.setState: state: "ACCEPTED"
2017/05/30 20:22:58 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:58 [TRACE] Waiting 400ms before next try
2017/05/30 20:22:59 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:59 [DEBUG] crud.BaseCrud.setState: state: "ACCEPTED"
2017/05/30 20:22:59 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:22:59 [TRACE] Waiting 800ms before next try
2017/05/30 20:23:00 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:23:00 [DEBUG] crud.BaseCrud.setState: state: "ACCEPTED"
2017/05/30 20:23:00 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:23:00 [TRACE] Waiting 1.6s before next try
2017/05/30 20:23:02 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/30 20:23:02 [DEBUG] crud.BaseCrud.setState: state: "FAILED"
2017/05/30 20:23:02 [DEBUG] root: eval: *terraform.EvalWriteState
2017/05/30 20:23:02 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/05/30 20:23:02 [DEBUG] root: eval: *terraform.EvalIf
2017/05/30 20:23:02 [DEBUG] root: eval: *terraform.EvalWriteState
2017/05/30 20:23:02 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/05/30 20:23:02 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/05/30 20:23:02 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* baremetal_load_balancer_listener.jmtfenv3-listener: Resource creation failed, state FAILED
2017/05/30 20:23:02 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* baremetal_load_balancer_listener.jmtfenv3-listener: Resource creation failed, state FAILED
2017/05/30 20:23:02 [TRACE] [walkApply] Exiting eval tree: baremetal_load_balancer_listener.jmtfenv3-listener
2017/05/30 20:23:02 [DEBUG] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/05/30 20:23:02 [DEBUG] dag/walk: upstream errored, not walking "provider.baremetal (close)"
2017/05/30 20:23:02 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/05/30 20:23:02 [TRACE] Preserving existing state lineage "3671877d-31e2-4f3c-a0b0-3847b4806e1d"
Error applying plan:
2017/05/30 20:23:02 [DEBUG] plugin: waiting for all plugin processes to complete...

1 error(s) occurred:

* baremetal_load_balancer_listener.jmtfenv3-listener: 1 error(s) occurred:

* baremetal_load_balancer_listener.jmtfenv3-listener: Resource creation failed, state FAILED

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### LINKED ISSUE #134: Load Balancer Backend creation fails with " Code: MethodNotAllowed; ...  Message: Method Not Allowed"
## Description of the bug:

Resource "baremetal_load_balancer_backend" cannot be created.

```
Error applying plan:

2 error(s) occurred:

* baremetal_load_balancer_backend.webserver[0]: 1 error(s) occurred:

* baremetal_load_balancer_backend.webserver.0: Code: MethodNotAllowed; OPC Request ID: /4F170C23B5DE4EBF95A8E7AC276BE3E0/F237FBD82C9D4059B4EF189ACC5FD2CF; Message: Method Not Allowed
* baremetal_load_balancer_backend.webserver[1]: 1 error(s) occurred:

* baremetal_load_balancer_backend.webserver.1: Code: MethodNotAllowed; OPC Request ID: /AC5DB34E90E44CD5A6523DC41ADE93CB/905C1DB9BEF74062BCB1D78A30212F2E; Message: Method Not Allowed

```

## A self-contained terraform file that reproduces the issue:

See attached zip file.
[lbtest.zip](https://github.com/oracle/terraform-provider-baremetal/files/1042611/lbtest.zip)

### LINKED ISSUE #135: Load Balancer Backend creation fails in v1.0.12 which works in v1.0.11
## Description of the bug:
Its another regression. Falls under the same category in which something used to work in previous version/release does not works in latest version.

Can you please take care of all lbaas related resource in one bundle, test it properly and then release. See from release version v1.0.9 lbaas related resources either has issues or regression in later. 

## A self-contained terraform file that reproduces the issue:

Your plan was also saved to the path below. Call the "apply" subcommand
with this plan file and Terraform will exactly execute this execution
plan.

Path: jmtfenv4.plan

+ baremetal_load_balancer_backend.jmtfenv3-backendapp01
    backendset_name:  "jmtst_backendset"
    backup:           "false"
    drain:            "false"
    ip_address:       "172.16.0.23"
    load_balancer_id: "ocid1.loadbalancer.oc1.phx.aaaaaaaaxaefhxouvt7iznpbpbqxrlryqh6mqzamvkz6ei35t6xpzh2atkua"
    name:             "<computed>"
    offline:          "false"
    port:             "8000"
    state:            "<computed>"
    weight:           "1"

Plan: 1 to add, 0 to change, 0 to destroy.

ing for all plugin processes to complete...
2017/05/31 16:12:20 [DEBUG] plugin: terraform: null-provider (internal) 2017/05/31 16:12:20 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/05/31 16:12:20 [DEBUG] plugin: /home/opc/terraform/bm_plugin/linux_amd64/terraform-provider-baremetal: plugin process exited
2017/05/31 16:12:20 [DEBUG] plugin: /usr/bin/terraform: plugin process exited
2017/05/31 16:12:20 [DEBUG] plugin: /usr/bin/terraform: plugin process exited
[opc@jmtst_provvm jmtfenv4]$ terraform apply jmtfenv4.plan
2017/05/31 16:12:26 [INFO] Terraform version: 0.9.4  277bbf65d1141207dbb30485bf124b1dba08f80f
2017/05/31 16:12:26 [INFO] Go runtime version: go1.8
2017/05/31 16:12:26 [INFO] CLI args: []string{"/usr/bin/terraform", "apply", "jmtfenv4.plan"}
2017/05/31 16:12:26 [DEBUG] Detected home directory from env var: /home/opc
2017/05/31 16:12:26 [DEBUG] Detected home directory from env var: /home/opc
2017/05/31 16:12:26 [DEBUG] Attempting to open CLI config file: /home/opc/.terraformrc
2017/05/31 16:12:26 [INFO] CLI command args: []string{"apply", "jmtfenv4.plan"}
2017/05/31 16:12:26 [INFO] command: initializing local backend from plan (not set)
2017/05/31 16:12:26 [DEBUG] Detected home directory from env var: /home/opc
2017/05/31 16:12:26 [INFO] command: backend initialized: *local.Local
2017/05/31 16:12:26 [INFO] backend/local: starting Apply operation
2017/05/31 16:12:26 [INFO] terraform: building graph: GraphTypeApply
"172.16.0.23", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
2017/05/31 16:12:26 [DEBUG] Resource state not found for "baremetal_load_balancer_backend.jmtfenv3-backendapp01": baremetal_load_balancer_backend.jmtfenv3-backendapp01
2017/05/31 16:12:26 [DEBUG] ReferenceTransformer: "provider.baremetal" references: []
2017/05/31 16:12:26 [DEBUG] ReferenceTransformer: "baremetal_load_balancer_backend.jmtfenv3-backendapp01" references: []
2017/05/31 16:12:26 [DEBUG] Starting graph walk: walkApply
2017/05/31 16:12:26 [DEBUG] dag/walk: added new vertex: "meta.count-boundary (count boundary fixup)"
2017/05/31 16:12:26 [DEBUG] dag/walk: added new vertex: "provider.baremetal (close)"
2017/05/31 16:12:26 [DEBUG] dag/walk: added new vertex: "root"
2017/05/31 16:12:26 [DEBUG] dag/walk: added new vertex: "baremetal_load_balancer_backend.jmtfenv3-backendapp01"
2017/05/31 16:12:26 [DEBUG] dag/walk: added new vertex: "provider.baremetal"
2017/05/31 16:12:26 [DEBUG] dag/walk: added edge: "root" waiting on "provider.baremetal (close)"
2017/05/31 16:12:26 [DEBUG] dag/walk: added edge: "baremetal_load_balancer_backend.jmtfenv3-backendapp01" waiting on "provider.baremetal"
2017/05/31 16:12:26 [DEBUG] dag/walk: added edge: "meta.count-boundary (count boundary fixup)" waiting on "baremetal_load_balancer_backend.jmtfenv3-backendapp01"
2017/05/31 16:12:26 [DEBUG] dag/walk: added edge: "provider.baremetal (close)" waiting on "baremetal_load_balancer_backend.jmtfenv3-backendapp01"
2017/05/31 16:12:26 [DEBUG] dag/walk: added edge: "root" waiting on "meta.count-boundary (count boundary fixup)"
2017/05/31 16:12:26 [DEBUG] dag/walk: dependencies changed for "root", sending new deps
2017/05/31 16:12:26 [DEBUG] dag/walk: dependencies changed for "baremetal_load_balancer_backend.jmtfenv3-backendapp01", sending new deps
2017/05/31 16:12:26 [DEBUG] dag/walk: dependencies changed for "meta.count-boundary (count boundary fixup)", sending new deps
2017/05/31 16:12:26 [DEBUG] dag/walk: dependencies changed for "provider.baremetal (close)", sending new deps
2017/05/31 16:12:26 [DEBUG] dag/walk: walking "provider.baremetal"
2017/05/31 16:12:26 [DEBUG] vertex 'root.provider.baremetal': walking
2017/05/31 16:12:26 [DEBUG] vertex 'root.provider.baremetal': evaluating
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalSequence
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalInitProvider
2017/05/31 16:12:26 [DEBUG] plugin: starting plugin: /home/opc/terraform/bm_plugin/linux_amd64/terraform-provider-baremetal []string{"/home/opc/terraform/bm_plugin/linux_amd64/terraform-provider-baremetal"}
2017/05/31 16:12:26 [DEBUG] plugin: waiting for RPC address for: /home/opc/terraform/bm_plugin/linux_amd64/terraform-provider-baremetal
2017/05/31 16:12:26 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/31 16:12:26 [INFO] terraform-provider-baremetal v1.0.12
2017/05/31 16:12:26 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/31 16:12:26 [DEBUG] plugin: plugin address: unix /tmp/plugin577902054
2017/05/31 16:12:26 [DEBUG] root: eval: terraform.EvalNoop
2017/05/31 16:12:26 [DEBUG] root: eval: terraform.EvalNoop
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalOpFilter
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalSequence
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalGetProvider
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalInterpolate
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalBuildProviderConfig
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalSetProviderConfig
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalOpFilter
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalSequence
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalConfigProvider
2017/05/31 16:12:26 [DEBUG] dag/walk: walking "baremetal_load_balancer_backend.jmtfenv3-backendapp01"
2017/05/31 16:12:26 [DEBUG] vertex 'root.baremetal_load_balancer_backend.jmtfenv3-backendapp01': walking
2017/05/31 16:12:26 [DEBUG] vertex 'root.baremetal_load_balancer_backend.jmtfenv3-backendapp01': evaluating
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalSequence
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalInstanceInfo
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalReadDiff
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalIf
2017/05/31 16:12:26 [DEBUG] root: eval: terraform.EvalNoop
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalIf
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalInterpolate
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalGetProvider
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalReadState
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalValidateResource
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalDiff
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalReadDiff
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalCompareDiff
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalGetProvider
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalReadState
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalApplyPre
baremetal_load_balancer_backend.jmtfenv3-backendapp01: Creating...
  backendset_name:  "" => "jmtst_backendset"
  backup:           "" => "false"
  drain:            "" => "false"
  ip_address:       "" => "172.16.0.23"
  load_balancer_id: "" => "ocid1.loadbalancer.oc1.phx.aaaaaaaaxaefhxouvt7iznpbpbqxrlryqh6mqzamvkz6ei35t6xpzh2atkua"
  name:             "" => "<computed>"
  offline:          "" => "false"
  port:             "" => "8000"
  state:            "" => "<computed>"
  weight:           "" => "1"
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalApply
2017/05/31 16:12:26 [DEBUG] apply: baremetal_load_balancer_backend.jmtfenv3-backendapp01: executing Apply
2017/05/31 16:12:26 [DEBUG] plugin: terraform-provider-baremetal: 2017/05/31 16:12:26 [DEBUG] No meta timeoutkey found in Apply()
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalWriteState
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalIf
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalWriteState
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/05/31 16:12:26 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/05/31 16:12:26 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* baremetal_load_balancer_backend.jmtfenv3-backendapp01: Code: MethodNotAllowed; OPC Request ID: /AD8962D702824724A42689C43E3B6324/AF9A34805DEE4FB8AC56D1C5B1A434BE; Message: Method Not Allowed
2017/05/31 16:12:26 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* baremetal_load_balancer_backend.jmtfenv3-backendapp01: Code: MethodNotAllowed; OPC Request ID: /AD8962D702824724A42689C43E3B6324/AF9A34805DEE4FB8AC56D1C5B1A434BE; Message: Method Not Allowed
2017/05/31 16:12:26 [TRACE] [walkApply] Exiting eval tree: baremetal_load_balancer_backend.jmtfenv3-backendapp01
2017/05/31 16:12:26 [DEBUG] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/05/31 16:12:26 [DEBUG] dag/walk: upstream errored, not walking "provider.baremetal (close)"
2017/05/31 16:12:26 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/05/31 16:12:26 [TRACE] Preserving existing state lineage "4c58d6ff-5915-4571-8b1f-8a007b21bceb"
Error applying plan:

1 error(s) occurred:

* baremetal_load_balancer_backend.jmtfenv3-backendapp01: 1 error(s) occurred:

* baremetal_load_balancer_backend.jmtfenv3-backendapp01: Code: MethodNotAllowed; OPC Request ID: /AD8962D702824724A42689C43E3B6324/AF9A34805DEE4FB8AC56D1C5B1A434BE; Message: Method Not Allowed

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### PR DESCRIPTION
**Pull request by mikejihbe**
Closes #119, closes #100, closes LB related issues to backend creation "Method not allowed" and listener SSL configuration issues (closes #135, closes #134, closes #131, closes #132).

### CODE REVIEW

File: resource_obmcs_loadbalancer_loadbalancer.go [hunk 1]
```diff
@@ -228,6 +230,10 @@ func (s *LoadBalancerResourceCrud) SetData() {
 
 // Delete makes a request to delete the load balancer
 func (s *LoadBalancerResourceCrud) Delete() (e error) {
+	// TODO: make sure this actually works
+	if strings.Contains(s.D.Id(), "ocid1.loadbalancerworkrequest") {
+		return
+	}
```
Comment (codycushing) [inline resource_obmcs_loadbalancer_loadbalancer.go]: Is this still a todo or is the functionality verified now?
